### PR TITLE
version bumps

### PR DESCRIPTION
**Pull request by MasseGuillaume**
used published scala-library
bump Dotty version
bump sbt version
use Dotty specific example

### CODE REVIEW

**Comment by felixmulder** [comment]
Build fails, otherwise the changes LGTM. We should probably start publishing this on LAMP instead, make it part of the nightly builds.

**Comment by MasseGuillaume** [comment]
It's a bug in sbt 0.13.13. It works fine in 0.13.11

**Comment by MasseGuillaume** [comment]
https://github.com/sbt/sbt/issues/2895

**Comment by MasseGuillaume** [comment]
ty ;-). Can you publish 0.1.6 ?

**Comment by felixmulder** [comment]
I would love to, especially since you're being such a good boy and fixing things 😄 

Unfortunately, I can't get to my GPG key from here - I'll publish it first thing Monday morning.

**Comment by felixmulder** [comment]
Published :tada:

**Pull request merged**
